meta_product_name: "Happy Tasks"
meta_title: "Happy Tasks - The best task management app for neuroatypical children"
meta_description: "Happy Tasks: The ultimate task management app designed for neuroatypical children. Empower routines, build focus, and make organizing fun and accessible for every child!"
meta_image: "happyTasks-neurodiverse.png" # should exist in `app/assets/images/`
meta_url: "https://happy-tasks.click"
